py37:
  image: python:3.7
  script:
  - pip install tox
  - tox -e py37

py38:
  image: python:3.8
  script:
  - pip install tox
  - tox -e py38

py39:
  image: python:3.9
  script:
  - pip install tox
  - tox -e py39

py310:
  image: python:3.10
  script:
  - pip install tox
  - tox -e docs,format,mypy,py310,package,pep8

pages:
  image: python:3.10
  script:
  - pip install sphinx pydata-sphinx-theme .
  - rm -rf docs/source
  - sphinx-apidoc -e -f -o docs/reference/source/ src/hypercorn
  - sphinx-build -b html docs/ docs/_build/html/
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.h2spec-script: &h2spec-script
  image: python:3.10
  script:
  - python3 -m pip install trio .
  - cd compliance/h2spec && nohup hypercorn --keyfile key.pem --certfile cert.pem -k $WORKER_CLASS server:App &
  - wget https://github.com/summerwind/h2spec/releases/download/v2.2.0/h2spec_linux_amd64.tar.gz
  - tar -xvf h2spec_linux_amd64.tar.gz
  - sleep 10
  - ./h2spec -tk -h 127.0.0.1 -p 8000 -o 10

h2spec:
  <<: *h2spec-script
  variables:
    WORKER_CLASS: "asyncio"

h2spec-trio:
  <<: *h2spec-script
  variables:
    WORKER_CLASS: "trio"

.autobahn-script: &autobahn-script
  image: python:2.7.16-alpine3.10
  script:
  - apk --update add build-base libressl libressl-dev ca-certificates libffi-dev python3 python3-dev
  - pip install pyopenssl==19.1.0 cryptography==2.3.1 autobahntestsuite
  - python3 -m pip install trio .
  - cd compliance/autobahn && nohup hypercorn -k $WORKER_CLASS server:App &
  - while ! netstat -l -t | grep -q 8000; do sleep 1; done
  - cd compliance/autobahn && wstest -m fuzzingclient && python summarise.py
  artifacts:
    paths:
    - compliance/autobahn/reports/servers/

autobahn:
  <<: *autobahn-script
  variables:
    WORKER_CLASS: "asyncio"

autobahn-trio:
  <<: *autobahn-script
  variables:
    WORKER_CLASS: "trio"
